# Generated by Django 5.1.1 on 2024-11-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattitle',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='chattitle',
            name='subadminID',
        ),
        migrations.DeleteModel(
            name='ChatBody',
        ),
        migrations.DeleteModel(
            name='ChatTitle',
        ),
    ]
